lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_4/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_message', message_post, name='add_message'),
    url(r'^result_table', message_table, name='result_table')

]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
#import lab_5.urls as lab_5
import lab_2_addon.urls as lab_2_addon
import lab_6.urls as lab_6
#import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(url='/lab-4/', permanent='True'),name='index'),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    #url(r'^lab-5/', include(lab_5,namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    #url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    #url(r'^$', index_lab1, name='index'),
]

lab_4/models.py
from django.db import models

class Message(models.Model):

    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

lab_4/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid' : 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

lab_4/views.py
from django.shortcuts import render
from lab_2.views import landing_page_content
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

# Create your views here.
response = {'author': "Naomi"}#TODO Implement yourname
about_me = ['INFx',
            'SaltyCinnamonRoll',
            'Pasta:3',
            'Designing',
            'Dunno',
            'OK',
            'Nothing.']

def index(request):
    response['content'] = landing_page_content
    html = 'lab_4/lab_4.html'

    # TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['about_me'] = about_me
    response['message_form'] = Message_Form
    return render(request, html, response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'], message=response['message'])
        message.save()
        html = 'lab_4/form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/lab-4')

def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'lab_4/table.html'
    return render(request, html, response)

lab_4/templates/lab_4/form_result.html
{% extends "lab_4/layout/base.html" %}
{% block title %}Pesan dari {{ name }}{% endblock %}
{% block content %}
<textarea readonly rows="5" class="form-control">&quot;{{ message }}&quot;-{{ name }}
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p>&copy; {{ name }}</p>
{% endblock %}

lab_4/templates/lab_4/lab_4.html
{%  extends "lab_4/layout/base.html" %}
{% block content %}

<style>
    .portofolio, .bio_title, .list_title, .send_message_title{
        text-align: center;
        font-size: 50px;
        padding-top: 20px;
        padding-bottom: 20px;

    }

    .portofolio{
        background-color: #ffccff;
        color: #ff80ff;
    }

    .bio_title{
        background-color: #ecdfff;
        color: #b380ff;
    }

    .list_title{
        background-color: #dfecff;
        color: #4d94ff;
    }

    .send_message_title{
        background-color: #ccffff;
        color: #00b3b3;
    }

    #list{
        background-color: #e6f0ff;
        color: #4d94ff;
    }

    #form{
        background-color: #e6ffff;
        color: #00b3b3;
    }

    .img-circle {
        border-radius: 50%;
        width: 200px;
        height: 200px;
    }

</style>

<div class="portofolio">
    <h1>Portofolio</h1>
    <img class="img-circle" src="https://pbs.twimg.com/profile_images/842381333817049088/_PDgDOIG_400x400.jpg">
</div>

<div class="bio">
    <div class="bio_title">
        <h2>Bio</h2>
    </div>

    <div style="text-align: center; background-color:#e8e3ff">
        <p style="font-size: 20px; padding-top: 50px; padding-bottom: 50px; color:#b380ff">
            {{ content }}
        </p>
    </div>
</div>

<section class="about_me">
    <div class="list_title">
        <h2>List</h2>
    </div>

    <ul id="list" style="font-size: 20px; padding-top: 50px; padding-bottom: 50px">
        {% for ii in about_me %}
        <li> {{ ii }}</li>
        {% endfor %}
    </ul>

</section>

<section name="form">
<!---------------TITLE-------------->
    <div class="send_message_title">
        <h2>Send Message</h2>
    </div>

    <!------------------------------FORM-------------------------------->
    <form id="form" method="POST" action="{% url 'lab-4:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default" style="color: #00b3b3">Submit</button>
    </form>

</section>

{% endblock %}

lab_4/templates/lab_4/table.html
{% extends "lab_4/layout/base.html" %}
{% block title %} List of Messages {% endblock %}

{% block content %}
<table class="table"  style="background-color: #f2e5ff">
    <thead style="color: #b695ff">
        <th>Name</th>
        <th>Email</th>
        <th>Message</th>
        <th>Time submitted</th>
    </thead>
    <tbody>
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning" style="background-color: #ffb59d; color: #ff8a80"> {% else %} <tr class="success" style="background-color: #c1ffa8; color: #64ff63;">
            {% endif %}
            <td>{{ i.name }}</td>
            <td>{{ i.email }}</td>
            <td>{{ i.message }}</td>
            <td>{{ i.created_date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}